//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _543 {
            get {
                object obj = ResourceManager.GetObject("543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5431 {
            get {
                object obj = ResourceManager.GetObject("5431", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade&gt;
        ///  &lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;HAAR&lt;/featureType&gt;
        ///  &lt;height&gt;100&lt;/height&gt;
        ///  &lt;width&gt;100&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;boostType&gt;GAB&lt;/boostType&gt;
        ///    &lt;minHitRate&gt;9.9500000476837158e-01&lt;/minHitRate&gt;
        ///    &lt;maxFalseAlarm&gt;5.0000000000000000e-01&lt;/maxFalseAlarm&gt;
        ///    &lt;weightTrimRate&gt;9.4999999999999996e-01&lt;/weightTrimRate&gt;
        ///    &lt;maxDepth&gt;1&lt;/maxDepth&gt;
        ///    &lt;maxWeakCount&gt;100&lt;/maxWeakCount&gt;&lt;/stageParams&gt;
        ///  &lt;featureParams&gt;
        ///    &lt;maxCatCount&gt;0&lt;/maxCat [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cascade {
            get {
                return ResourceManager.GetString("cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade&gt;
        ///  &lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;HAAR&lt;/featureType&gt;
        ///  &lt;height&gt;20&lt;/height&gt;
        ///  &lt;width&gt;60&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;boostType&gt;GAB&lt;/boostType&gt;
        ///    &lt;minHitRate&gt;9.9500000476837158e-001&lt;/minHitRate&gt;
        ///    &lt;maxFalseAlarm&gt;5.0000000000000000e-001&lt;/maxFalseAlarm&gt;
        ///    &lt;weightTrimRate&gt;9.4999999999999996e-001&lt;/weightTrimRate&gt;
        ///    &lt;maxDepth&gt;1&lt;/maxDepth&gt;
        ///    &lt;maxWeakCount&gt;100&lt;/maxWeakCount&gt;&lt;/stageParams&gt;
        ///  &lt;featureParams&gt;
        ///    &lt;maxCatCount&gt;0&lt;/maxCatCount&gt;
        ///    &lt;fe [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string haarcascade_russian_plate_number {
            get {
                return ResourceManager.GetString("haarcascade_russian_plate_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test1 {
            get {
                object obj = ResourceManager.GetObject("test1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap енрп {
            get {
                object obj = ResourceManager.GetObject("енрп", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
